# Generated by Django 4.2.2 on 2023-06-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCGlobalData',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('totalQuestions', models.IntegerField(default=-1)),
                ('totalEasy', models.IntegerField(default=-1)),
                ('totalMedium', models.IntegerField(default=-1)),
                ('totalHard', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('totalSolved', models.IntegerField()),
                ('easySolved', models.IntegerField()),
                ('mediumSolved', models.IntegerField()),
                ('hardSolved', models.IntegerField()),
                ('acceptanceRate', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('contributionPoints', models.IntegerField()),
                ('reputation', models.IntegerField()),
            ],
        ),
    ]
