# Generated by Django 4.2.2 on 2023-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lcglobaldata_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcglobaldata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
