# Generated by Django 4.2.3 on 2023-08-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
